/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

/**
 *
 * @author Vespertino
 */
public class Geek extends javax.swing.JFrame {

    /**
     * Creates new form Geek
     */
    public Geek() {
        initComponents();
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/geek-----.gif")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barbilla = new javax.swing.JCheckBox();
        gafas = new javax.swing.JCheckBox();
        pelo = new javax.swing.JCheckBox();
        dientes = new javax.swing.JCheckBox();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barbilla.setText("Barbilla");
        barbilla.setFocusable(false);
        barbilla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barbilla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barbilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbillaActionPerformed(evt);
            }
        });

        gafas.setText("Gafas");
        gafas.setFocusable(false);
        gafas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gafas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gafas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gafasActionPerformed(evt);
            }
        });

        pelo.setText("Pelo");
        pelo.setFocusable(false);
        pelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peloActionPerformed(evt);
            }
        });

        dientes.setText("Dientes");
        dientes.setFocusable(false);
        dientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dientesActionPerformed(evt);
            }
        });

        imagen.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gafas)
                            .addComponent(barbilla))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dientes)
                            .addComponent(pelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(barbilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gafas)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dientes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barbillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbillaActionPerformed
        // TODO add your handling code here:
        if (barbilla.isSelected()) {
            imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/geek-c---.gif")));
        } else if (!barbilla.isSelected()) {
            imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/geek-----.gif")));

        }
    }//GEN-LAST:event_barbillaActionPerformed

    private void gafasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gafasActionPerformed
        // TODO add your handling code here:
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/geek-----.gif")));
    }//GEN-LAST:event_gafasActionPerformed

    private void peloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peloActionPerformed
        // TODO add your handling code here:
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/geek-----.gif")));
    }//GEN-LAST:event_peloActionPerformed

    private void dientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dientesActionPerformed
        // TODO add your handling code here:
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/geek-----.gif")));
    }//GEN-LAST:event_dientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Geek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Geek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Geek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Geek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Geek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox barbilla;
    private javax.swing.JCheckBox dientes;
    private javax.swing.JCheckBox gafas;
    private javax.swing.JLabel imagen;
    private javax.swing.JCheckBox pelo;
    // End of variables declaration//GEN-END:variables
}
