/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Toolkit;

/**
 *
 * @author Vespertino
 */
public class Marcador_baloncesto extends javax.swing.JFrame {

    boolean activado = false;

    /**
     * Creates new form Marcador_baloncesto
     */
    public Marcador_baloncesto() {
        initComponents();
        Seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Visitante = new javax.swing.JLabel();
        ManresaBoton2 = new javax.swing.JButton();
        ManresaBoton1 = new javax.swing.JButton();
        VisitanteBoton2 = new javax.swing.JButton();
        VisitanteBoton1 = new javax.swing.JButton();
        corregir = new javax.swing.JButton();
        Manresa = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marcador baloncesto");
        setAlwaysOnTop(true);
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Manresa");

        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("Visitante");

        Visitante.setBackground(new java.awt.Color(255, 255, 255));
        Visitante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Visitante.setText("0");
        Visitante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Visitante.setOpaque(true);

        ManresaBoton2.setBackground(new java.awt.Color(204, 0, 0));
        ManresaBoton2.setText("2 Puntos");
        ManresaBoton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ManresaBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManresaBoton2ActionPerformed(evt);
            }
        });

        ManresaBoton1.setBackground(new java.awt.Color(204, 0, 0));
        ManresaBoton1.setText("1 Punto");
        ManresaBoton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ManresaBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManresaBoton1ActionPerformed(evt);
            }
        });

        VisitanteBoton2.setBackground(java.awt.Color.blue);
        VisitanteBoton2.setText("2 Puntos");
        VisitanteBoton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VisitanteBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitanteBoton2ActionPerformed(evt);
            }
        });

        VisitanteBoton1.setBackground(java.awt.Color.blue);
        VisitanteBoton1.setText("1 Punto");
        VisitanteBoton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VisitanteBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitanteBoton1ActionPerformed(evt);
            }
        });

        corregir.setBackground(new java.awt.Color(102, 0, 0));
        corregir.setText("Corregir");
        corregir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        corregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corregirActionPerformed(evt);
            }
        });

        Manresa.setBackground(new java.awt.Color(255, 255, 255));
        Manresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Manresa.setText("0");
        Manresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Manresa.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Manresa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Visitante, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManresaBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VisitanteBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManresaBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VisitanteBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(corregir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manresa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Visitante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManresaBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisitanteBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManresaBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisitanteBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(corregir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(249, 268));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManresaBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManresaBoton2ActionPerformed
        // TODO add your handling code here:
        String s, aux;
        int i=0, auxx;
        aux = Manresa.getText();
        auxx = Integer.parseInt(aux);
        if (activado == true) {
            if (auxx <= 1) {

            } else {
                i = auxx - 2;
            }

        } else {
            i = auxx + 2;

        }

        s = Integer.toString(i);
        Manresa.setText(s);
    }//GEN-LAST:event_ManresaBoton2ActionPerformed

    private void VisitanteBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitanteBoton2ActionPerformed
        // TODO add your handling code here:
        String s, aux;
        int i=0, auxx;
        aux = Visitante.getText();
        auxx = Integer.parseInt(aux);

        if (activado == true) {
            if (auxx <= 1) {

            } else {
                i = auxx - 2;
            }

        } else {
            i = auxx + 2;

        }
        s = Integer.toString(i);
        Visitante.setText(s);
    }//GEN-LAST:event_VisitanteBoton2ActionPerformed

    private void ManresaBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManresaBoton1ActionPerformed
        // TODO add your handling code here:
        String s, aux;
        int i=0, auxx;
        aux = Manresa.getText();
        auxx = Integer.parseInt(aux);
        if (activado == true) {
            if (auxx <= 0) {

            } else {
                i = auxx - 1;
            }

        } else {
            i = auxx + 1;

        }
        s = Integer.toString(i);
        Manresa.setText(s);
    }//GEN-LAST:event_ManresaBoton1ActionPerformed

    private void VisitanteBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitanteBoton1ActionPerformed
        // TODO add your handling code here:
        String s, aux;
        int i=0, auxx;
        aux = Visitante.getText();
        auxx = Integer.parseInt(aux);
        if (activado == true) {
            if (auxx <= 0) {

            } else {
                i = auxx - 1;
            }

        } else {
            i = auxx + 1;

        }
        s = Integer.toString(i);
        Visitante.setText(s);
    }//GEN-LAST:event_VisitanteBoton1ActionPerformed

    private void corregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corregirActionPerformed
        // TODO add your handling code here:
        if (activado == false) {
            activado = true;
        } else {
            activado = false;
        }
    }//GEN-LAST:event_corregirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcador_baloncesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcador_baloncesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcador_baloncesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcador_baloncesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marcador_baloncesto().setVisible(true);
            }
        });
    }
    
    private void Seticon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Manresa;
    private javax.swing.JButton ManresaBoton1;
    private javax.swing.JButton ManresaBoton2;
    private javax.swing.JLabel Visitante;
    private javax.swing.JButton VisitanteBoton1;
    private javax.swing.JButton VisitanteBoton2;
    private javax.swing.JButton corregir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
